version: '3.8'

services:
  # سرویس MongoDB
  mongodb:
    image: mongo:5.0
    container_name: twitter-monitor-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGODB_DB:-twitter_monitor}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - twitter-monitor-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # خدمت بک‌اند
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${ENVIRONMENT:-development}
    container_name: twitter-monitor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/${MONGODB_DB:-twitter_monitor}?authSource=admin
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-true}
      - APP_START_TIME=${APP_START_TIME}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - twitter-monitor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # خدمت فرانت‌اند
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${ENVIRONMENT:-development}
    container_name: twitter-monitor-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - frontend_logs:/app/logs
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - twitter-monitor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  twitter-monitor-network:
    driver: bridge

volumes:
  mongo_data:
    name: twitter-monitor-mongodb-data
  backend_logs:
    name: twitter-monitor-backend-logs
  frontend_logs:
    name: twitter-monitor-frontend-logs